

services:
  minio:
    build:
      context: .
      target: runtime
    container_name: minio-multistage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  minio-data:
    driver: local
